#!/usr/bin/env python3
"""
import_purify_data.py — derives real per-species Purify costs from Niantic's
raw GAME_MASTER. Same source and approach as the other import_*.py scripts.

WHY THIS EXISTS
----------------
Scout has no Purify function at all yet. Purifying a Shadow Pokemon costs
Stardust and Candy that scale by species rarity, confirmed against multiple
independent sources: 1,000/1 for common species, 3,000/3 for
starters/uncommon, 5,000/5 for rare, up to 20,000/20 for Legendaries.

SCHEMA NOTE
------------
pokemonSettings.kmBuddyDistance (the walking distance to earn a candy as a
buddy) maps directly onto the purify cost tier: stardust = km * 1000,
candy = km. Verified against known examples before trusting the formula at
scale: Pidgey (1km) -> 1,000/1, Bulbasaur (3km) -> 3,000/3, Snorlax/Dratini
(5km) -> 5,000/5, Mewtwo/Raikou (20km, Legendary) -> 20,000/20 — all match
published purification costs exactly.

Species name matching follows the same NAME_OVERRIDES/pretty_name approach
as import_evolution_data.py and import_movepool_data.py, since the app keys
everything by lowercase OCR-derived display name.
"""
import json
import urllib.request

SOURCE_URL = "https://raw.githubusercontent.com/PokeMiners/game_masters/master/latest/latest.json"

NAME_OVERRIDES = {
    "MR_MIME": "Mr. Mime",
    "MR_RIME": "Mr. Rime",
    "MIME_JR": "Mime Jr.",
    "FARFETCHD": "Farfetch'd",
    "SIRFETCHD": "Sirfetch'd",
    "HO_OH": "Ho-Oh",
    "PORYGON_Z": "Porygon-Z",
    "JANGMO_O": "Jangmo-o",
    "HAKAMO_O": "Hakamo-o",
    "KOMMO_O": "Kommo-o",
    "NIDORAN_FEMALE": "Nidoran\u2640",
    "NIDORAN_MALE": "Nidoran\u2642",
    "TYPE_NULL": "Type: Null",
    "FLABEBE": "Flab\u00e9b\u00e9",
    "WO_CHIEN": "Wo-Chien",
    "CHIEN_PAO": "Chien-Pao",
    "TING_LU": "Ting-Lu",
    "CHI_YU": "Chi-Yu",
}


def fetch_gamemaster(path=None):
    if path:
        with open(path) as f:
            return json.load(f)
    with urllib.request.urlopen(SOURCE_URL) as r:
        return json.load(r)


def pretty_name(pokemon_id):
    if pokemon_id in NAME_OVERRIDES:
        return NAME_OVERRIDES[pokemon_id]
    words = pokemon_id.replace("-", "_").split("_")
    return " ".join(w.capitalize() for w in words)


def extract_purify_costs(gamemaster):
    found = {}
    for entry in gamemaster:
        template_id = entry.get("templateId", "")
        if "COPY" in template_id:
            continue
        ps = entry.get("data", {}).get("pokemonSettings")
        if not ps:
            continue
        km = ps.get("kmBuddyDistance")
        if not km:
            continue
        pokemon_id = ps.get("pokemonId")
        if not pokemon_id or pokemon_id in found:
            continue
        found[pretty_name(pokemon_id).lower()] = {
            "stardust": int(km * 1000),
            "candy": int(km),
        }
    return found


def to_js_literal(table):
    lines = ["const PURIFY_COST_TABLE = {"]
    for name in sorted(table.keys()):
        rec = table[name]
        lines.append(
            "  %s: { stardust: %d, candy: %d }," % (json.dumps(name), rec["stardust"], rec["candy"])
        )
    lines.append("};")
    return "\n".join(lines)


if __name__ == "__main__":
    import sys
    local_path = sys.argv[1] if len(sys.argv) > 1 else None
    gm = fetch_gamemaster(local_path)
    table = extract_purify_costs(gm)
    print("// Generated by scripts/import_purify_data.py from Niantic GAME_MASTER", file=sys.stderr)
    print("// %d species with purify cost data" % len(table), file=sys.stderr)
    print(to_js_literal(table))
