#!/usr/bin/env python3
"""
import_mega_data.py — pulls real per-species Mega Evolution energy costs from
Niantic's raw GAME_MASTER (via PokeMiners' community mirror), the same source
and same authority tier as import_move_data.py, and writes them out as an
embeddable JS object literal for pokemon-mechanics.js.

WHY THIS EXISTS
----------------
Scout's manual megaEnergyInventory (name + amount, hand-entered) had no idea
what a species' Mega Evolve actually costs, so the app could never tell you
whether you had enough or how much a repeat evolve would take. This script
gives that a real per-species cost table.

SOURCE
------
  https://raw.githubusercontent.com/PokeMiners/game_masters/master/latest/latest.json

SCHEMA NOTES
------------
- A species has Mega Evolution if pokemonSettings.evolutionBranch contains at
  least one entry with `temporaryEvolutionEnergyCost` set. Entries without it
  are ordinary (non-temporary) evolutions and are skipped.
- `temporaryEvolutionEnergyCost` is the FIRST-time cost; the entry always
  contains `temporaryEvolutionEnergyCostSubsequent` too, which is the repeat
  cost the game charges every time after the first for that species (this is
  species-level, not per-individual Pokemon — matches how megaEnergyInventory
  already treats energy).
- Some species (Charizard, Mewtwo, Raichu) have two branches — MEGA_X and
  MEGA_Y — both listed under the same species; both are kept as separate
  named forms under that one species key, since a trainer can hold energy
  toward either and the two costs happen to always match each other in the
  raw data but are modeled as distinct in case that ever changes.
- Templates with "COPY" in the templateId are dated legacy duplicates
  (e.g. a Community Day snapshot) and are skipped — first non-COPY occurrence
  of a given pokemonId wins, matching import_move_data.py's dedup approach.
- Verified: 58 species found, cost tiers are 100/20, 200/40, 300/60, 400/80,
  and 7500/150 (Mewtwo Mega X/Y only) — this matches the tier costs known
  from the live game, cross-checked against community values before shipping.
"""
import json
import urllib.request

SOURCE_URL = "https://raw.githubusercontent.com/PokeMiners/game_masters/master/latest/latest.json"


def fetch_gamemaster(path=None):
    if path:
        with open(path) as f:
            return json.load(f)
    with urllib.request.urlopen(SOURCE_URL) as r:
        return json.load(r)


def extract_mega_costs(gamemaster):
    found = {}
    for entry in gamemaster:
        template_id = entry.get("templateId", "")
        if "COPY" in template_id:
            continue
        ps = entry.get("data", {}).get("pokemonSettings")
        if not ps:
            continue
        branch = ps.get("evolutionBranch")
        if not branch:
            continue
        # Only TEMP_EVOLUTION_MEGA[/_X/_Y] — TEMP_EVOLUTION_PRIMAL (Groudon,
        # Kyogre) has the same cost-shaped fields but is Primal Reversion, a
        # different mechanic with its own resource, not Mega Energy. Sweeping
        # it in here would silently mislabel it in the Mega Evolution UI.
        mega_branches = [
            b for b in branch
            if b.get("temporaryEvolutionEnergyCost")
            and b.get("temporaryEvolution", "").startswith("TEMP_EVOLUTION_MEGA")
        ]
        if not mega_branches:
            continue
        pokemon_id = ps.get("pokemonId")
        if not pokemon_id or pokemon_id in found:
            continue
        forms = []
        for b in mega_branches:
            temp_evo = b["temporaryEvolution"]
            # TEMP_EVOLUTION_MEGA -> "", TEMP_EVOLUTION_MEGA_X -> "x", _Y -> "y"
            suffix = temp_evo.replace("TEMP_EVOLUTION_MEGA", "").replace("_", "").lower()
            forms.append({
                "form": suffix,
                "first": b["temporaryEvolutionEnergyCost"],
                "subsequent": b["temporaryEvolutionEnergyCostSubsequent"],
            })
        found[pokemon_id.lower()] = forms
    return found


def to_js_literal(costs):
    lines = ["const MEGA_EVOLUTION_COSTS = {"]
    for name in sorted(costs.keys()):
        forms = costs[name]
        forms_js = ", ".join(
            "{ form: %s, first: %d, subsequent: %d }" % (
                json.dumps(f["form"]), f["first"], f["subsequent"]
            )
            for f in forms
        )
        lines.append("  %s: [%s]," % (json.dumps(name), forms_js))
    lines.append("};")
    return "\n".join(lines)


if __name__ == "__main__":
    import sys
    local_path = sys.argv[1] if len(sys.argv) > 1 else None
    gm = fetch_gamemaster(local_path)
    costs = extract_mega_costs(gm)
    print("// Generated by scripts/import_mega_data.py from Niantic GAME_MASTER", file=sys.stderr)
    print("// %d species with Mega Evolution data" % len(costs), file=sys.stderr)
    print(to_js_literal(costs))
