// Sample Pokémon data for demo/testing
// Replace this with your real Poke Genie export via IMPORT CSV
// NEVER commit real scan data to git

const SAMPLE_POKEMON = [
  {
    "idx": 1,
    "name": "Dragonite",
    "form": null,
    "dex": 149,
    "gender": "male",
    "cp": 3521,
    "hp": 156,
    "atkIV": 15,
    "defIV": 14,
    "staIV": 13,
    "ivAvg": 93.3,
    "lvlMin": 35.0,
    "lvlMax": 35.0,
    "quickMove": "Dragon Breath",
    "chargeMove": "Dragon Claw",
    "chargeMove2": "Hurricane",
    "scanDate": null,
    "catchDate": "2026-07-15",
    "weight": "210.5 kg",
    "height": "2.21 m",
    "lucky": false,
    "shadowPurified": "0",
    "favorite": true,
    "dust": 5000,
    "great": {"rankPct": 82.4, "rankNum": 1245, "statProd": 1854321, "dustCost": 10000, "candyCost": 10, "evolvesTo": null},
    "ultra": {"rankPct": 91.2, "rankNum": 342, "statProd": 2456789, "dustCost": 5000, "candyCost": 5, "evolvesTo": null},
    "little": {"rankPct": null, "rankNum": null, "statProd": null, "dustCost": null, "candyCost": null, "evolvesTo": null}
  },
  {
    "idx": 2,
    "name": "Garchomp",
    "form": null,
    "dex": 445,
    "gender": "female",
    "cp": 3189,
    "hp": 182,
    "atkIV": 14,
    "defIV": 15,
    "staIV": 12,
    "ivAvg": 91.1,
    "lvlMin": 33.5,
    "lvlMax": 33.5,
    "quickMove": "Mud Shot",
    "chargeMove": "Earth Power",
    "chargeMove2": "Outrage",
    "scanDate": null,
    "catchDate": "2026-07-20",
    "weight": "95.0 kg",
    "height": "1.90 m",
    "lucky": true,
    "shadowPurified": "0",
    "favorite": false,
    "dust": 3000,
    "great": {"rankPct": 78.9, "rankNum": 2103, "statProd": 1723456, "dustCost": 15000, "candyCost": 15, "evolvesTo": null},
    "ultra": {"rankPct": 88.5, "rankNum": 567, "statProd": 2345678, "dustCost": 8000, "candyCost": 8, "evolvesTo": null},
    "little": {"rankPct": null, "rankNum": null, "statProd": null, "dustCost": null, "candyCost": null, "evolvesTo": null}
  },
  {
    "idx": 3,
    "name": "Metagross",
    "form": null,
    "dex": 376,
    "gender": "",
    "cp": 3794,
    "hp": 148,
    "atkIV": 15,
    "defIV": 15,
    "staIV": 15,
    "ivAvg": 100.0,
    "lvlMin": 40.0,
    "lvlMax": 40.0,
    "quickMove": "Bullet Punch",
    "chargeMove": "Meteor Mash",
    "chargeMove2": "Earthquake",
    "scanDate": null,
    "catchDate": "2026-06-30",
    "weight": "550.0 kg",
    "height": "1.60 m",
    "lucky": false,
    "shadowPurified": "0",
    "favorite": true,
    "dust": 10000,
    "great": {"rankPct": 65.2, "rankNum": 4521, "statProd": 1456789, "dustCost": 20000, "candyCost": 20, "evolvesTo": null},
    "ultra": {"rankPct": 85.1, "rankNum": 890, "statProd": 2123456, "dustCost": 12000, "candyCost": 12, "evolvesTo": null},
    "little": {"rankPct": null, "rankNum": null, "statProd": null, "dustCost": null, "candyCost": null, "evolvesTo": null}
  },
  {
    "idx": 4,
    "name": "Tyranitar",
    "form": "Shadow",
    "dex": 248,
    "gender": "male",
    "cp": 3412,
    "hp": 165,
    "atkIV": 13,
    "defIV": 12,
    "staIV": 14,
    "ivAvg": 86.7,
    "lvlMin": 30.0,
    "lvlMax": 30.0,
    "quickMove": "Smack Down",
    "chargeMove": "Stone Edge",
    "chargeMove2": "Crunch",
    "scanDate": null,
    "catchDate": "2026-07-25",
    "weight": "202.0 kg",
    "height": "2.00 m",
    "lucky": false,
    "shadowPurified": "1",
    "favorite": false,
    "dust": 8000,
    "great": {"rankPct": 72.1, "rankNum": 3102, "statProd": 1567890, "dustCost": 18000, "candyCost": 18, "evolvesTo": null},
    "ultra": {"rankPct": 81.3, "rankNum": 1234, "statProd": 1987654, "dustCost": 10000, "candyCost": 10, "evolvesTo": null},
    "little": {"rankPct": null, "rankNum": null, "statProd": null, "dustCost": null, "candyCost": null, "evolvesTo": null}
  },
  {
    "idx": 5,
    "name": "Mewtwo",
    "form": null,
    "dex": 150,
    "gender": "",
    "cp": 4168,
    "hp": 179,
    "atkIV": 15,
    "defIV": 13,
    "staIV": 14,
    "ivAvg": 93.3,
    "lvlMin": 40.0,
    "lvlMax": 40.0,
    "quickMove": "Confusion",
    "chargeMove": "Psystrike",
    "chargeMove2": "Focus Blast",
    "scanDate": null,
    "catchDate": "2026-07-10",
    "weight": "122.0 kg",
    "height": "2.01 m",
    "lucky": false,
    "shadowPurified": "0",
    "favorite": true,
    "dust": 15000,
    "great": {"rankPct": 45.8, "rankNum": 6789, "statProd": 1234567, "dustCost": 50000, "candyCost": 50, "evolvesTo": null},
    "ultra": {"rankPct": 62.3, "rankNum": 3456, "statProd": 1678901, "dustCost": 30000, "candyCost": 30, "evolvesTo": null},
    "little": {"rankPct": null, "rankNum": null, "statProd": null, "dustCost": null, "candyCost": null, "evolvesTo": null}
  }
];

// Export for DC runtime
if (typeof window !== 'undefined') {
  window.POKEMON_DATA = SAMPLE_POKEMON;
  window.dispatchEvent(new CustomEvent('scout-data-ready'));
}

export default SAMPLE_POKEMON;
